"""Installed-pair golden fixture — the producer's real bytes through the fork's reader.

The fixture under ``fixtures/conductor-catalog-golden/`` was generated by
cao-conductor's real capture+publish path (head ``5895e6c``, see the
fixture's README) and vendored byte-identical.  These tests serve it
through the real FastAPI app and assert the installed-pair contract:
the four golden record shapes read back through ``GET /communications``,
every served body equals its content object byte for byte, every
response is ``Cache-Control: no-store``, and a corrupted content object
is refused by digest with no body bytes served.

Unlike ``test_communications_catalog_api.py`` — which publishes
synthetic indexes to probe the reader's edges — nothing here is
hand-written: if these tests fail, the seam between the two
repositories moved, not the test data.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from unittest.mock import patch

import pytest

from cli_agent_orchestrator.services import communications_catalog as catalog

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "conductor-catalog-golden")

#: The vendored index is the installed-pair contract.  Regenerating the
#: fixture upstream changes this digest (wall-clock fields alone do not:
#: they are inside the JSON), so any re-vendoring must land here too.
VENDORED_INDEX_SHA256 = "6f23015d74f0388f5e9ecd7470167408147414f19e877b862be5b7be2fc54bae"

TASK = "occ-golden-0001"
PROJECT = "golden-project"

# The four deterministic communication ids, oldest to newest (the index's
# insertion order).  Fixed across regenerations per the fixture README.
OLDEST_TO_NEWEST = [
    "5a0d1c01-7a21-4e6f-8a30-000000000001",  # assignment
    "5a0d1c02-7a21-4e6f-8a30-000000000002",  # checkpoint, intermediate scope
    "5a0d1c03-7a21-4e6f-8a30-000000000003",  # report, final, file-snapshot
    "5a0d1c04-7a21-4e6f-8a30-000000000004",  # report, final, message-only
]


def _vendored_index() -> dict:
    with open(os.path.join(FIXTURE_DIR, "communications.json"), encoding="utf-8") as fh:
        return json.load(fh)


def _content_bytes(blob_id: str) -> bytes:
    with open(os.path.join(FIXTURE_DIR, "communications", "content", blob_id), "rb") as fh:
        return fh.read()


def test_vendored_index_is_unmodified():
    """The vendored bytes are what the tests below describe."""
    with open(os.path.join(FIXTURE_DIR, "communications.json"), "rb") as fh:
        raw = fh.read()
    assert hashlib.sha256(raw).hexdigest() == VENDORED_INDEX_SHA256
    # Every content object still digests to its own filename.
    for blob_id in _vendored_index()["content_objects"]:
        assert hashlib.sha256(_content_bytes(blob_id)).hexdigest() == blob_id


@pytest.fixture
def root(tmp_path):
    """The vendored fixture copied into a scratch conductor state root."""
    scratch = tmp_path / "cao-conductor"
    scratch.mkdir()
    shutil.copytree(FIXTURE_DIR, scratch / PROJECT)
    with patch.object(catalog, "catalog_root", return_value=str(scratch)):
        yield str(scratch)


class TestInstalledPairList:
    def test_the_four_golden_records_read_back_through_the_list_route(self, client, root):
        response = client.get(f"/communications?task_occurrence_id={TASK}")
        assert response.status_code == 200
        assert response.headers["cache-control"] == "no-store"
        payload = response.json()
        assert payload["schema"] == "cao-communications-index-v1"
        assert payload["coverage"] == "complete"
        assert payload["reasons"] == []
        assert payload["total"] == 4
        assert payload["next_cursor"] is None
        comms = payload["communications"]
        # The publisher's total order: recorded_at DESC, id ASC.
        assert [c["communication_id"] for c in comms] == list(reversed(OLDEST_TO_NEWEST))
        assert {c["kind"] for c in comms} == {"assignment", "checkpoint", "report"}
        reports = [c for c in comms if c["kind"] == "report"]
        assert len(reports) == 2
        assert sorted(c["report_scope"] for c in reports) == ["final", "final"]
        checkpoints = [c for c in comms if c["kind"] == "checkpoint"]
        assert [c["report_scope"] for c in checkpoints] == ["intermediate"]
        assert all(c["task_occurrence_id"] == TASK for c in comms)
        # The producer publishes goal_version as a store INTEGER (the
        # assignment carries 1); the reader normalises it to the string
        # spelling its own API contract promises.
        assignment = next(c for c in comms if c["kind"] == "assignment")
        assert assignment["goal_version"] == "1"
        # Metadata only: no body bytes ride the list surface.
        assert all("content" not in c for c in comms)


class TestInstalledPairDetail:
    def test_all_four_bodies_equal_their_content_object_bytes(self, client, root):
        by_id = {c["communication_id"]: c for c in _vendored_index()["communications"]}
        assert set(by_id) == set(OLDEST_TO_NEWEST)
        for comm_id, record in by_id.items():
            expected = _content_bytes(record["body"]["sha256"]).decode("utf-8")
            response = client.get(f"/communications/{comm_id}")
            assert response.status_code == 200, comm_id
            assert response.headers["cache-control"] == "no-store", comm_id
            payload = response.json()
            assert payload["reason"] is None, comm_id
            assert payload["content"] == expected, comm_id
            assert payload["communication"]["kind"] == record["kind"], comm_id

    def test_dangerous_assignment_body_is_served_verbatim_as_data(self, client, root):
        """The assignment body carries the attack payloads on purpose: the
        reader's job is faithful bytes over an inert JSON surface; making
        them harmless is the renderer's boundary (design §9), tested web-side."""
        assignment = next(
            c for c in _vendored_index()["communications"] if c["kind"] == "assignment"
        )
        expected = _content_bytes(assignment["body"]["sha256"]).decode("utf-8")
        assert "<script>" in expected
        assert "javascript:" in expected
        response = client.get(f"/communications/{assignment['communication_id']}")
        assert response.status_code == 200
        assert response.json()["content"] == expected


class TestInstalledPairAttachment:
    def test_file_backed_report_serves_through_the_attachment_route(self, client, root):
        file_backed = next(
            c
            for c in _vendored_index()["communications"]
            if c["body"] and c["body"].get("capture_kind") == "file-snapshot"
        )
        attachment_id = file_backed["body"]["attachment_id"]
        expected = _content_bytes(file_backed["body"]["sha256"]).decode("utf-8")

        response = client.get(f"/communications/attachments/{attachment_id}")
        assert response.status_code == 200
        assert response.headers["cache-control"] == "no-store"
        payload = response.json()
        assert payload["reason"] is None
        assert payload["document"]["display_name"] == "report.md"
        assert payload["document"]["media_type"] == "text/markdown"
        # Digest verification passed and the exact published bytes came back.
        assert payload["content"] == expected


class TestCorruptedContentObject:
    def test_a_flipped_byte_is_a_typed_refusal_and_no_body_is_served(self, client, tmp_path):
        """One flipped byte inside one content object must produce the PR 9B
        refusal vocabulary — same-length bytes pass the size check and fail
        the digest check — and neither the original nor the corrupted text
        may appear anywhere in the response.  The vendored fixture itself is
        never touched: the corruption happens in the tmp_path copy."""
        scratch = tmp_path / "cao-conductor"
        scratch.mkdir()
        shutil.copytree(FIXTURE_DIR, scratch / PROJECT)

        assignment = next(
            c for c in _vendored_index()["communications"] if c["kind"] == "assignment"
        )
        blob_id = assignment["body"]["sha256"]
        object_path = scratch / PROJECT / "communications" / "content" / blob_id
        data = bytearray(object_path.read_bytes())
        data[0] ^= 0x01
        corrupted = bytes(data)
        object_path.write_bytes(corrupted)

        with patch.object(catalog, "catalog_root", return_value=str(scratch)):
            response = client.get(f"/communications/{assignment['communication_id']}")

        assert response.status_code == 503
        assert response.json()["detail"] == "content-digest-mismatch"
        assert "Golden assignment" not in response.text
        assert corrupted.decode("utf-8", errors="replace") not in response.text

    def test_the_corrupted_copy_never_touched_the_vendored_original(self):
        assignment = next(
            c for c in _vendored_index()["communications"] if c["kind"] == "assignment"
        )
        assert hashlib.sha256(_content_bytes(assignment["body"]["sha256"])).hexdigest() == (
            assignment["body"]["sha256"]
        )
